function mGenerateVhdr(BLOCKPATH,dataFile,markerFile,channelNum,sampleRate,headerFile)
% dataFile = 'lfp1.bin';
% markerFile = 'subj0.vmrk';
% channelNum = 64;
% sampleRate = fs;
fid = fopen(fullfile(BLOCKPATH,headerFile), 'w');

vhdrString1 = ['Brain Vision Data Exchange Header File Version 1.0\r\n'...
'; Data created by the Vision Recorder\r\n\r\n'];

vhdrString2 = ['[Common Infos]\r\n'...
'Codepage=UTF-8\r\n'...
'DataFile=' dataFile '\r\n'...
'MarkerFile=' markerFile '\r\n'...
'DataFormat=BINARY\r\n'...
'; Data orientation: MULTIPLEXED=ch1,pt1, ch2,pt1 ...\r\n'...
'DataOrientation=MULTIPLEXED\r\n'...
'NumberOfChannels=' num2str(channelNum) '\r\n'...
'; Sampling interval in microseconds\r\n'...
'SamplingInterval=' num2str(1e6/sampleRate) ']\r\n\r\n'];

vhdrString3 = ['[Binary Infos]\r\n'...
'BinaryFormat=INT_16\r\n\r\n'];

vhdrString4 = ['[Channel Infos]\r\n'...
'; Each entry: Ch<Channel number>=<Name>,<Reference channel name>,\r\n'...
'; <Resolution in "Unit">,<Unit>, Future extensions..\r\n'...
'; Fields are delimited by commas, some fields might be omitted (empty).\r\n'...
'; Commas in channel names are coded as "\\1".];\r\n'];

vhdrString5 = channelsToVhdr(channelNum,sampleRate);

vhdrOutput = [vhdrString1 vhdrString2 vhdrString3 vhdrString4 vhdrString5];

fprintf(fid,vhdrOutput);
fclose(fid);
